# Generated by Django 5.1 on 2026-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, default='', max_length=255)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('specialist', 'Specialist'), ('other', 'Other')], default='other', max_length=50)),
                ('date_of_service', models.DateField(blank=True, null=True)),
                ('total_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_allowed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patient_responsibility', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('original_file', models.FileField(blank=True, upload_to='bills/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_code', models.CharField(blank=True, max_length=10, null=True)),
                ('hcpcs_code', models.CharField(blank=True, max_length=10, null=True)),
                ('icd10_codes', models.JSONField(blank=True, default=list)),
                ('description_raw', models.TextField(blank=True, default='')),
                ('description_plain', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('charged_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regional_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_level', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
                ('error_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
