# Generated by Django 5.1 on 2026-04-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_lineitem_flag_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='parse_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bill',
            name='parse_status',
            field=models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error')], default='ok', max_length=20),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
    ]
