# Generated by Django 5.1 on 2026-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_parse_message_bill_parse_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('disputed', 'Disputed'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='new', max_length=20),
        ),
    ]
