# Generated by Django 5.1 on 2026-04-02 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('denied', 'Denied')], default='draft', max_length=20)),
                ('letter_content', models.TextField(blank=True, default='')),
                ('letter_pdf', models.FileField(blank=True, null=True, upload_to='disputes/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('savings_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='bills.bill')),
                ('line_items', models.ManyToManyField(blank=True, related_name='disputes', to='bills.lineitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
