# Generated by Django 5.1 on 2026-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPTPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('national_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CPT Price Cache',
                'verbose_name_plural': 'CPT Price Caches',
            },
        ),
    ]
