# Generated by Django 5.1 on 2026-04-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('mac_name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'CMS Locality',
                'verbose_name_plural': 'CMS Localities',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ZipLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('state', models.CharField(max_length=2)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='pricing.cmslocality')),
            ],
            options={
                'verbose_name': 'ZIP-to-Locality Mapping',
                'verbose_name_plural': 'ZIP-to-Locality Mappings',
            },
        ),
        migrations.CreateModel(
            name='CMSPriceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_code', models.CharField(db_index=True, max_length=10)),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('non_facility_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facility_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='pricing.cmslocality')),
            ],
            options={
                'verbose_name': 'CMS Price Entry',
                'verbose_name_plural': 'CMS Price Entries',
                'indexes': [models.Index(fields=['cpt_code', 'year'], name='pricing_cms_cpt_cod_b38a56_idx')],
                'unique_together': {('cpt_code', 'locality', 'year')},
            },
        ),
    ]
