# Generated by Django 5.1 on 2026-04-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_cmslocality_ziplocality_cmspriceentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cmspriceentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cmspriceentry',
            name='locality',
        ),
        migrations.CreateModel(
            name='LocalityGPCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(db_index=True, max_length=7)),
                ('loc_description', models.CharField(blank=True, default='', max_length=250)),
                ('mac', models.CharField(blank=True, default='', max_length=5)),
                ('gpci_work', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('gpci_pe', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('gpci_mp', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('year', models.IntegerField(default=2026)),
            ],
            options={
                'verbose_name': 'Locality GPCI',
                'verbose_name_plural': 'Locality GPCIs',
                'unique_together': {('locality', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ProcedureRVU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcpc', models.CharField(db_index=True, max_length=10)),
                ('modifier', models.CharField(blank=True, default='', max_length=2)),
                ('short_description', models.CharField(blank=True, default='', max_length=120)),
                ('proc_stat', models.CharField(blank=True, default='', max_length=1)),
                ('rvu_work', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('full_nfac_pe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('full_fac_pe', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('rvu_mp', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('conv_fact', models.DecimalField(decimal_places=4, default=33.4009, max_digits=10)),
                ('pctc', models.CharField(blank=True, default='', max_length=2)),
                ('global_period', models.CharField(blank=True, default='', max_length=5)),
                ('year', models.IntegerField(default=2026)),
            ],
            options={
                'verbose_name': 'Procedure RVU',
                'verbose_name_plural': 'Procedure RVUs',
                'indexes': [models.Index(fields=['hcpc', 'year'], name='pricing_pro_hcpc_1fd040_idx')],
                'unique_together': {('hcpc', 'modifier', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ZipToLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, max_length=5)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('carrier', models.CharField(max_length=5)),
                ('locality_code', models.CharField(max_length=2)),
                ('year', models.IntegerField(default=2026)),
            ],
            options={
                'verbose_name': 'ZIP-to-Locality',
                'verbose_name_plural': 'ZIP-to-Locality Mappings',
                'unique_together': {('zip_code', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='ZipLocality',
        ),
        migrations.DeleteModel(
            name='CMSLocality',
        ),
        migrations.DeleteModel(
            name='CMSPriceEntry',
        ),
    ]
