# Generated by Django 5.1 on 2026-06-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_failedloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_disclosure_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
